
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-5pm-8
owner: ucsb-cs156-s24
repo_name: team01-s24-5pm-8
pull_requests: [{"author":{"id":"U_kgDOBdCSgA","is_bot":false,"login":"Hannahshakouri01","name":"Hannah Shakouri"},"headRefName":"Hannah-ZipCode-Controller","number":31,"title":" hs- finished controller and tests for Zipcode","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/31"}]
