
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-5pm-8
owner: ucsb-cs156-s24
repo_name: team01-s24-5pm-8
pull_requests: [{"author":{"id":"MDQ6VXNlcjQzMDE2ODM5","is_bot":false,"login":"KarstenLansing","name":"Karsten James Lansing"},"headRefName":"Karsten-TidesQuery","number":25,"title":"Add Tides Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/25"},{"author":{"id":"U_kgDOBcwBsg","is_bot":false,"login":"bradygin","name":"Brady Gin"},"headRefName":"Brady-University-Controller","number":24,"title":"Add University Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/24"},{"author":{"id":"U_kgDOBcwBsg","is_bot":false,"login":"bradygin","name":"Brady Gin"},"headRefName":"Brady-University","number":23,"title":"Add University Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/23"},{"author":{"id":"U_kgDOB3DoXA","is_bot":false,"login":"TheRealAndrxw","name":"Andrew Vosgueritchian"},"headRefName":"Andrew-PublicHoliday","number":22,"title":"Add PublicHoliday Service","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/22"},{"author":{"id":"U_kgDOB00C0g","is_bot":false,"login":"spark686","name":""},"headRefName":"Sungchae-Location-Controller","number":21,"title":"Add Location Controller and Test","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/21"},{"author":{"id":"U_kgDOB00C0g","is_bot":false,"login":"spark686","name":""},"headRefName":"Sungchae-Location","number":20,"title":"Add Location Service and Test","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/20"},{"author":{"id":"MDQ6VXNlcjQyMTYwOTky","is_bot":false,"login":"xinyao-song","name":"XinYao Song"},"headRefName":"Xinyao-Joke-Controller","number":19,"title":"Add Joke Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/19"},{"author":{"id":"MDQ6VXNlcjQyMTYwOTky","is_bot":false,"login":"xinyao-song","name":"XinYao Song"},"headRefName":"Xinyao-Joke","number":18,"title":"Add Joke Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/18"}]
