
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-5pm-8
owner: ucsb-cs156-s24
repo_name: team01-s24-5pm-8
pull_requests: [{"author":{"id":"MDQ6VXNlcjQyMTYwOTky","is_bot":false,"login":"xinyao-song","name":"XinYao Song"},"headRefName":"Xinyao-HomeController","number":29,"title":" Customize Home Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/29"},{"author":{"id":"MDQ6VXNlcjQzMDE2ODM5","is_bot":false,"login":"KarstenLansing","name":"Karsten James Lansing"},"headRefName":"Karsten-READMEupdate","number":28,"title":"Update README.md","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/28"},{"author":{"id":"U_kgDOBdCSgA","is_bot":false,"login":"Hannahshakouri01","name":"Hannah Shakouri"},"headRefName":"Hannah-ZipCode","number":27,"title":"Add ZipCode Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/27"},{"author":{"id":"MDQ6VXNlcjQzMDE2ODM5","is_bot":false,"login":"KarstenLansing","name":"Karsten James Lansing"},"headRefName":"Karsten-TidesQuery-Controller","number":26,"title":"Add Tides Controller and Tests ","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/26"},{"author":{"id":"U_kgDOBcwBsg","is_bot":false,"login":"bradygin","name":"Brady Gin"},"headRefName":"Brady-University-Controller","number":24,"title":"Add University Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/24"},{"author":{"id":"U_kgDOBcwBsg","is_bot":false,"login":"bradygin","name":"Brady Gin"},"headRefName":"Brady-University","number":23,"title":"Add University Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/23"},{"author":{"id":"U_kgDOB3DoXA","is_bot":false,"login":"TheRealAndrxw","name":"Andrew Vosgueritchian"},"headRefName":"Andrew-PublicHoliday","number":22,"title":"Add PublicHoliday Service","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/22"},{"author":{"id":"U_kgDOB00C0g","is_bot":false,"login":"spark686","name":""},"headRefName":"Sungchae-Location-Controller","number":21,"title":"Add Location Controller and Test","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/21"},{"author":{"id":"MDQ6VXNlcjQyMTYwOTky","is_bot":false,"login":"xinyao-song","name":"XinYao Song"},"headRefName":"Xinyao-Joke-Controller","number":19,"title":"Add Joke Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/pull/19"}]
